### ISSUE TITLE
Allow user to mute/unmute rather than stopping/starting audio stream

### ISSUE THREAD

**Issue by akhirsch** [clowdr-app/clowdr#10]
If you enter a room, turn off your microphone, and then turn it back on, you get a desync between your video and microphone that is quite distracting.

Muting seems to work better, but the "turn off microphone" button is much more prominent.

**Comment by EdNutting** [comment]
Hi Akhirsch,

This may be fixed in our latest version deployed last night. Please let us know if you continue to have this issue after hard-refreshing your browser today.

You make a good suggestion - we will look into whether it's possible to mute vs stop microphone in future.

**Comment by rossng** [comment]
Yep, we need to implement a 'true' mute button - one that continues publishing an empty audio stream rather than actually terminating the WebRTC stream and then restarting it. This issue will track progress on that.
