### ISSUE TITLE
Participant list behavior

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#101]
Another try at how lists of participants in rooms in the left sidebar should work... 

Clicking on the room name pops up a list of participants in the room with a “Go to room” button at the top.  (This has a good side effect: At the moment, people have reported being surprised when clicking something takes them away from their current room.  This makes the “take me away” an explicit operation.)  

And by the way, the more clicky design I’m advocating now does not need to involve any popovers: clicking a room name could also expand the room name to include the full participant list and the button to go to the room. (And I guess clicking on a person could just bring up a pair of buttons — either as a pop up or in the middle of a mobile device screen — “View Profile” and “Send DM”.)

Indeed, I think this would behave better from the UX point of view than the current auto-display way.  The problem with the current way is that sweeping the mouse across the list of rooms in the sidebar leads to a lot of long lists getting displayed and hidden, which can make it confusing to get your mouse over the room that you intended.

**Comment by rossng** [comment]
This UX has changed a lot now, closing as stale.
