### ISSUE TITLE
Shuffle room improvements

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#102]
- [x] The 30 second warning should count seconds down to 0.  And it should not be just the last 30 seconds -- it should start as soon as you enter the room.
- [x] Make shuffle rooms more random (e.g. by making the re-shuffler a bit reluctant to put people together who have already [recently] been together)
- [x] Do we still need this text?  "Updates every 60s - please help preserve our DB by not refreshing"

**Comment by rossng** [comment]
Item 2 is a duplicate of #33

**Comment by rossng** [comment]
All tasks split to specific issues.
