### ISSUE TITLE
Minor UI nits

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#103]
- [x] Right now there are four icons at the top of the chat pane (resizing, pinning, etc.); it would be nice to put them in a row
- [x] Someone asked for a "Feedback" button (that I guess would generate an email to Clowdr devs) 
- [x] We should suppress the "Social rooms" and "Program Rooms" headers in the left sidebar if there are only social rooms.  Similarly, there should be no Schedule button or sidebar area if the schedule is empty, and there should be no Sponsors area if there are no sponsors.
- [x] Chats that are just emotes don't show the name of the poster. They should.
- [x] The Create New Room dialog has two red asterisks whose semantics is not obvious.
- [x] The unread message counts in the chat list (and headers) should be red if possible.
- [x] Not sure if this is is easy to fix or not, but people have consistently missed the icons to close the sidebars.  Someone pointed out that one reason for this is that the X icon is not actually part of the left sidebar -- it is _above_ the sidebar in its own horizontal top-bar.  Moving it and its opposite icon on the right into their respective sidebars (maybe even moving everything into the sidebars and eliminating the top bar) would be more intuitive.

**Comment by rossng** [comment]
All issues split out
