### ISSUE TITLE
Misc video-room issues

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#106]
- [x] Having to start the camera explicitly every time you join any video space is a bit clunky
- [x] There should be a "Test audio" feature on the Join Room / Preview page
- [x] Looks like if someone has not made noise in a little while their video feed will be turned off even if there are only a couple of other feeds being displayed.  Don’t know if Vonage offers a way to tune this so that as many videos as possible stay on… it would be nice if so.
- [x] Keyboard shortcuts (e.g. esp for turning audio on and off) would be very nice.  Especially if they were the same as Zoom. :-)
- [x] An invariant of the UI should be that anyplace I see someone's name I can click to get both (a) their profile and (b) a button for sending them a DM 
- [x] What does the little headphone icon mean, on people's thumbnail pictures? If the answer is "not much", then can we delete it?
- [x] When screensharing an emacs window, the presenter's name gets overlayed on the minibuffer because it's the bottom-right corner of the screen :-(  Not sure what to do about this

**Comment by rossng** [comment]
> What does the little headphone icon mean, on people's thumbnail pictures? If the answer is "not much", then can we delete it?

This shows that the user has their microphone turned on but not their video. It's part of the default Vonage UI, but there are various [customisation options](https://tokbox.com/developer/guides/customize-ui/js/). Now that the basic rooms themselves are relatively stable, we can probably start looking at this kind of thing.

**Comment by rossng** [comment]
> There should be a "Test audio" feature on the Join Room / Preview page

We do display a volume meter (though Chrome likes disabling it by default). It's a bit janky atm though.

**Comment by bcpierce00** [comment]
> This shows that the user has their microphone turned on but not their video. It's part of the default Vonage UI, but there are various customisation options. Now that the basic rooms themselves are relatively stable, we can probably start looking at this kind of thing.

Ah, OK.  That is useful information, but a camera-with-a-slash icon would be much more intuitive.

**Comment by bcpierce00** [comment]
> We do display a volume meter (though Chrome likes disabling it by default). It's a bit janky atm though.

I mean more than that -- I want to be able to record a short sound clip and play it back to hear how my mic is sounding to others.

**Comment by rossng** [comment]
All issues have been split out.
