### ISSUE TITLE
Documentation for debugging A/V issues

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#107]
We should really provide a script to help people debug A/V problems.  E.g., most of the advice we gave to people this week could well be useful to others too.  Specifically:
       - web resources for debugging webcam issues
       - the advice to switch to Chrome if possible
       - the advice to fail over to a mobile device
       - (And probably these should be available through the UI, maybe via a "help" menu.  This would also be a place to provide a link to the GitHub page, etc.)

**Comment by rossng** [comment]
Partially addressed by https://clowdr.org/resources/mic-cam-permissions

**Comment by EdNutting** [comment]
I think https://clowdr.org/resources/mic-cam-permissions now fully addresses this to be honest.
