### ISSUE TITLE
Add a "you need to refresh" warning

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#109]
When we deploy a critical fix, we need to make sure people people are running the new code.  Since it's hard to get browsers to refresh, we should have a backup mechanism where people whose browsers do _not_ refresh automatically are shown a big warning message in the middle of their screen that says "A new version of the Clowdr client code is now available. Please refresh this window by pressing [whatever the appropriate key combo is on this browser]."

**Comment by EdNutting** [comment]
We now show a modal that blocks the whole page and asks the user to refresh (since a user-triggered refresh more reliably makes the browser pickup new files). Failing this, there is a 3 minute timeout that will trigger an automatic refresh and a progress bar in the modal indicates this to the user.
