### ISSUE TITLE
Wrong UX flow when clicking DM button on profile popup

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#111]
Clicking a person's name/picture in a chat, then clicking the DM button on the profile that pops up, will navigate away from the current room and brings up a private video chat with that person.  

This is both undesirable (I want to be able to DM people but keep listening to a talk or conversation) and surprising.  

Clicking the button should only affect the chat sidebar.

**Comment by EdNutting** [comment]
This was fixed recently.
