### ISSUE TITLE
Rooms can have negative people

### ISSUE THREAD

**Issue by akhirsch** [clowdr-app/clowdr#12]
Currently, the POPL room "Hallway 1" has -4 people in it. This has bounced between -4 and 0 for the last hour or so as people have come and gone.

I'm not sure what's causing it, but it's probably something to look into.

**Comment by hannelita** [comment]
<img width="325" alt="Screen Shot 2021-01-17 at 4 31 12 PM" src="https://user-images.githubusercontent.com/506426/104860369-39843a00-58f9-11eb-94bc-709b9f1088ee.png">
Confirming the bug

**Comment by EdNutting** [comment]
This is a counter for the number of people viewing the page. The count goes wrong due to a consistency issue in the database triggers at the moment. Will fix after POPL when we have more time to dig into whatever the async condition is that's causing it.

**Comment by EdNutting** [comment]
This got fixed for Friday when I completely re-implemented presence counts. They can never go negative now and are much more responsive (though we still have more work to do to improve them).
