### ISSUE TITLE
Login to Clowdr space broken

### ISSUE THREAD

**Issue by lennartberinger** [clowdr-app/clowdr#13]
After entering login credentials (using the link with the invite code embedded, or just by using the link that does not contain the code), only the top of the main page is shown with the buttons (incl "LogOut") near the top, but the rest of the page just shows the spinning wheel. Clearing history, quitting browser etc doesn't solve the issue - the only way to participate in the conference is to by pass Clowdr and go to the zoom room of a session (if you happen to know the zoom room...).This issue has been preventing me now to log back into Clowdr for 2h. I've given a few more details in a mail to Ed, Jon, Crista.

**Comment by lennartberinger** [comment]
Switching from Firefox to Opera (and Michael Greenberg quarterbacking things!) seems to have resolved the issue.

**Comment by bcpierce00** [comment]
Excellent!!

**Comment by EdNutting** [comment]
Closing in favour of reviewing our auth system based on lots of feedback from POPL already.
