### ISSUE TITLE
[Feature Request] Permanent Sidebar

### ISSUE THREAD

**Issue by yforster** [clowdr-app/clowdr#14]
On a big screen, it would be nice to have the sidebar there permanently rather than needing to click the icon in the top-left corner every time.

**Comment by bcpierce00** [comment]
Agreed!  This has been on my list too.  Even on a medium-sized screen (iPad, etc.), I'd rather have to explicitly dismiss it than have it go away by itself.

If this is an easy fix, I'd advocate making it soon.

**Comment by EdNutting** [comment]
For performance we can't do this at the moment, but will consider it in future.

**Comment by EdNutting** [comment]
This feature (along with a rework of navigation and layout in general) is landing in `main` this week.

**Comment by EdNutting** [comment]
This feature is now deployed.
