### ISSUE TITLE
Video turns off if person has not made noise for a while, even if below the max feeds threshold

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#142]
This could be potentially caused by many people in the room having only audio enabled. Our algorithm currently treats them as if they have video enabled, so if many audio-only participants speak, it will cause video-participants who did not speak recently to drop off the list of enabled videos.

**Comment by rossng** [comment]
Split from #106

**Comment by bcpierce00** [comment]
I don't think that's it.  I'm pretty sure I saw this behavior during talks,
when just one person was speaking and everyone else was quiet except for
maybe one or two people, and even so there were only 2-3 video feeds
showing.

>

**Comment by rossng** [comment]
Okay, that would be a legit bug. I'll keep an eye out for this behaviour.

It's likely that, in the nearish future, we'll refactor the sorting/enabling algo to unify the way it treats subscribers (people who have an audio/video stream) and connections (peers that do not have an audio/video stream). This bug might well get hit as part of that.

**Comment by EdNutting** [comment]
@rossng is (or was recently) investigating this

**Comment by EdNutting** [comment]
Ross recent fixes in e9c1259 hopefully fixed this.
