### ISSUE TITLE
Consider moving the close/open sidebar buttons into the sidebars themselves

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#154]
Some users have found it confusing that the buttons for expanding and collapsing the sidebars are in the top menu bar rather than attached to the sidebars themselves.

See Twitch's sidebar for an example.

**Comment by rossng** [comment]
Split from #103

**Comment by EdNutting** [comment]
We should also check what Twitch do on mobile to handle this.

**Comment by EdNutting** [comment]
This will be fixed when my commit lands in `main`.
