### ISSUE TITLE
Private rooms should be marked 'private' in the rooms list

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#158]
Private and small-group rooms should be marked "private" in the rooms list so that people don't get the impression that their private rooms are being shown to other people. (Ed: Technically they are, using the "lock" symbol, but I agree it's not obvious enough. They need to be in their own separate area. And the rooms page needs re-working.)

Split from #76

**Comment by EdNutting** [comment]
In the new UI released today, the lock icon is much more obvious, which I hope resolves this.
