### ISSUE TITLE
[Bug] Names on messages not being displayed

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr#16]
<img width="634" alt="Screen Shot 2021-01-18 at 10 10 58 AM" src="https://user-images.githubusercontent.com/506426/104933848-67a85f00-5977-11eb-9965-d6172802e8cb.png">
Fragment from T2 Liquid Haskell: Refinement Type Checker for Haskell

**Comment by yforster** [comment]
Are there any known workarounds for this bug? (different browser, different settings, ...)

**Comment by bcpierce00** [comment]
Unfortunately, it is coming from the middleware DB service (Haroku) that
Clowdr uses.  We are working on it.

**Comment by EdNutting** [comment]
This is "resolved" in so far as the names and profile pictures will be displayed whenever the data is available. We have a separate set of broader problems to resolve wrt database load/performance.
