### ISSUE TITLE
Make chat sidebar resizeable

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#161]
Split from #75

**Comment by bcpierce00** [comment]
Ed has observed that making it draggable is hard to implement.  IMO
offering just a couple of wider options and a button to cycle between them
would be OK

Alternatively, it might be OK to calculate the chat-sidebar size solely
based on window size -- i.e., make it wider only on windows that are
themselves wide.

>

**Comment by EdNutting** [comment]
The sidebar width is currently a (bounded) percentage of the overall window size. The percentage also changes at certain thresholds, and on small widths the "only one menu bar at a time" feature activates. I think the easy win here is as Benjamin suggests, to just have a tri-state button for cycling between "narrow, wide, full-width" (where "narrow" ~~ the current width)

**Comment by EdNutting** [comment]
We'll go with the button for adjusting the sizes -- your insane screen width is in the 0.01% club Benjamin ;) 

As a user with both sidebars open on a 2560x1440 resolution 25-inch screen, I do not want the chat sidebar any wider. My screen is still in the <1% of users globally.

Note that screen resolutions above 1920x1080 don't even feature on the stats for top screen sizes worldwide in 2020. Screen resolutions above 1080p are pretty rare even in our user group, who mostly follow the global trend of 1920x1080 and 1366x768 resolutions. 

In the UK for 2020, statcounter (who are a reasonably reliable source) rank 2560x1440 as just 2.88% of desktop users.

**Comment by bcpierce00** [comment]
Fair enough.

>

**Comment by EdNutting** [comment]
Fully resizable chat (inc. by mouse, touch or arrow keys) is now in `next` branch for release this month.

**Comment by bcpierce00** [comment]
Hooray!
