### ISSUE TITLE
Improve broadcast controls UI

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#178]
The broadcast controls UI needs to be clearer.

* Consider not using a popover
* Replace the 'suitcase' icon with something clearer
* Also consider not using an accordion

Split from #57

**Comment by EdNutting** [comment]
It'd be nice if we had an icon or image that graphically represented what each layout is.

**Comment by EdNutting** [comment]
Replaced icon and added "Stream layout" text to the button.
