### ISSUE TITLE
[Bug] Video arrangement in chat rooms is broken

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr#18]
When there are too many participants in a room, the alignment breaks (Chrome - MacOS), and the video gets out of the frame
![Screen Shot 2021-01-19 at 1 36 11 PM](https://user-images.githubusercontent.com/506426/105078462-0c9c6800-5a5c-11eb-95ad-4c17b09ea9f7.png)

**Comment by EdNutting** [comment]
I think we got this fixed during the week but I'll leave this issue open for now until I can check it.
