### ISSUE TITLE
Unify content people and event people

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#181]
We would like to unify the concept of content people and event people. Right now we have:

```
Attendee <-?- EventPerson --> Event
Attendee <-?- ContentPerson <-- ContentGroupPerson --> ContentGroup
```

And we are aiming for:

```
Attendee <-?- Person <-- EventPerson --> Event
Attendee <-?- Person <-- ContentPerson --> Event
```

Split from #48

**Comment by EdNutting** [comment]
Performing this remodeling will wipe out all existing EventPerson records. This is not a particular issue as they can be restored using the new, accompanying admin UI tools to copy from ContentPeople or add from Groups.
