### ISSUE TITLE
Keep last-edited row in focus in CRUD table

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#183]
In the schedule editor, changing the date/time of an event can cause it to move around in the list. (The same applies to any edits applied while the table is sorted.) Sometimes, the item will even move off the currently-selected page of the table and the user has to go and find it again.

This is not a great experience. We should probably keep our focus/pagination locked to the last-edited row until the user clicks a pagination button. If the row moves to another page, we follow it. It the row moves out of the viewport, we scroll to it.

Split from #47

**Comment by EdNutting** [comment]
This will be obsolete with the new admin UX as per Luke's designs.
