### ISSUE TITLE
Track video view counts

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#189]
Organisers are very interested in seeing how many views their videos (pre-recorded and live recordings) have. We should track the view counts of videos and display some statistics in the analytics page of the admin panel.

Note: it is highly likely that writing this directly to Postgres will have performance implications. We may need a separate service that handles these.

Split from #40

**Comment by rossng** [comment]
Related to #30

**Comment by EdNutting** [comment]
The realtime service is now handling view count tracking. The UI will submit a "item viewed" signal after 3s, 15s, 15s for content groups, played videos (content items) and room hls streams respectively. 

Data is temporarily stored in Redis. CronToGo batch writes the information into Hasura. The realtime service writes these back in batches to protect Postgres.

At the moment, only a single CronToGo job should be used, as the writeback code is not concurrency safe.

I have configured permissions for the respective stats tables, so if we get time we can display the view counts to admins or even attendees.

**Comment by EdNutting** [comment]
This is now completed (at least in its basic form, including the Analytics admin page)
