### ISSUE TITLE
Webcam on when it shouldn't be?

### ISSUE THREAD

**Issue by achlipala** [clowdr-app/clowdr#19]
At POPL 2021, I jumped from a hallway room to a lightning talk, and my webcam is telling me it's still on, with its usual light.  Is Clowdr keeping video/audio recording on for longer than needed, representing a privacy risk in case of bugs?

**Comment by EdNutting** [comment]
Thanks Adam. This is certainly an issue that we need to resolve. 

The video room components are global to the app, and when you jump room the app retains access to the cam/mic. We disconnect from the room as soon as the page changes (or you click 'leave room') as it invalidates the video-connection's session id. But the "preview cam/mic" elements of the page are trickier to destruct reliably without losing the ease of access that user's like. As a result, cam/mic currently sometimes remain in-use locally (but not 'publishing' i.e. uploading) to anywhere. I've seen a similar issue in Google Hangouts in the past.

We'll need to spend some time in each browser to work out the characteristics and find a reliable method for dropping the preview-use of the devices without then requiring extra clicks for users every time they join a new room.

**Comment by EdNutting** [comment]
After a few months of testing our fix and checking with users, we're now satisfied that we fixed this issue for the app as a whole.
