### ISSUE TITLE
Trackers?

### ISSUE THREAD

**Issue by spitters** [clowdr-app/clowdr#2]
Why send all the information to doubleclick

**Comment by EdNutting** [comment]
Sorry, we don't use any trackers. If there is a YouTube video embedded on a page, that might be what you're seeing. Clowdr only has its own internal mechanisms for tracking online status (which we don't currently do _any_ logging of and there is Incognito mode if you want to opt out of it).

**Comment by spitters** [comment]
Thanks for the clarification!
