### ISSUE TITLE
Bad error message when not logged in

### ISSUE THREAD

**Issue by achlipala** [clowdr-app/clowdr#20]
At POPL 2021, when I try to navigate directly to the "Rooms" page when not logged in, the error message about trouble loading data is quite opaque.  I wish it would say "log in, dude"!

**Comment by EdNutting** [comment]
I think this is part of two broader issues that we need to fix up:

* Our handling of "expected error" cases -- things where we need to direct the user to a remedial action
* Our handling of distributed system (i.e. remote component and network) failures -- we need to be testing the behaviour when these occur and providing users information and, where possible, actions they can take.
