### ISSUE TITLE
Migrate content admin panel to new CRUD table

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#202]
The content admin panel needs to be migrated to the new CRUD table, as frontend performance is currently unacceptably slow for large conferences.

**Comment by EdNutting** [comment]
This has now been completed, although three things are missing:

1. Combine videos button
2. Send individual submission request emails buttons
3. Is Logo layout control on images for sponsors

In addition, I have left a gap in the UI for more bulk-editing controls.

**Comment by EdNutting** [comment]
Feature parity achieved and links now direct to the new table. Closing this issue (with the sidenote that more bulk editing controls are on their way :) )
