### ISSUE TITLE
Allow users to flag/report chat messages

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#210]
This is a feature we used to have. For inclusivity, we need some kind of robust moderation system, and that includes the ability for users to report chat messages to organisers.

**Comment by rossng** [comment]
The chats panel in the admin UI can be used as the equivalent of the Moderation Hub that we had at CSCW/SPLASH.

**Comment by EdNutting** [comment]
Reporting/flagging of messages has now been implemented. There's still plenty of improvements to make, but the basic functionality is now there.
