### ISSUE TITLE
Allow organisers to segregate conference content and schedule for different groups of people

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#213]
This functionality is important as part of supporting co-events and workshops. Different groups of attendees need to be able to see different subsets of the overall conference content.

More general discussion about permission here: #212

**Comment by EdNutting** [comment]
This can now be applied to Elements (and to Uploadable Elements, but permissions for Uploadables are not enforced).

**Comment by EdNutting** [comment]
Ongoing work for subconferences and visibility controls has made this issue obsolete.
