### ISSUE TITLE
Unify content rendering

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#219]
We render content groups/items in lots of different places. Unfortunately, those places use a mish-mash of different and inconsistent logic. We should unify this into a single rendering system that is configurable for the different scenarios it is used in.

**Comment by rossng** [comment]
In particular, video rendering should be unified so that we can benefit globally from things like saving the subtitles preference.

**Comment by EdNutting** [comment]
Most element rendering is now unified and also making use of the priority number from the layout data. The last bits left to topple are:

1. Using the 2-column layout everywhere
2. Unify rendering on the Upload and Admin pages with the main attendee UI
3. Re-work the Admin Sponsors table to be a derivative of the main Content table. Add "Is logo" option to the Content V2 editor.

**Comment by EdNutting** [comment]
These items have now been completed.
