### ISSUE TITLE
Provide certificates of attendance

### ISSUE THREAD

**Issue by EdNutting** [clowdr-app/clowdr#227]
**Is your feature request related to a problem? Please describe.**

Description from client: Conference organisers are often asked to provide certificates of attendance, for the whole conference and also particular workshops or tutorials. This is easy at physical conferences but not so at virtual conferences.

Additional interpretation: They need to know the person actually showed up, not just registered without attending. At a physical conference, they'd just look at which badges had been picked up. At a virtual conference, they need a system to see who logged in and attended for at least the majority of the time of a given event.

**Describe the solution you'd like**

* The ability to set certain events as "tracked attendance"
* A label in the UI to notify attendees that attendance is being tracked
* An automatic report in the admin UI of which attendees showed up for which events.
* A way to automatically email attendees with certificates of attendance
* A way to download a complete set of certificates of attendees, possibly for a particular affiliation (e.g. to provide a report to a particular university or employer)

**Additional context**

* We should take into account potential privacy concerns.

**Comment by bcpierce00** [comment]
Is this something that we're hearing is a high priority for a lot of conferences?  Seems like it could involve some pretty tricky design / engineering work to get right.

**Comment by EdNutting** [comment]
This is not a high priority at this time.

**Comment by EdNutting** [comment]
We introduced End of Event Participation Surveys in November to address this for IBM.
