### ISSUE TITLE
[Feature Request] Chat width resize?

### ISSUE THREAD

**Issue by fbanados** [clowdr-app/clowdr#23]
On maximized windows, the chat takes considerable space that could be used for the videocall instead.  Maybe if we could close the chat just like the sidebar or resize the chat it would be nice.

**Comment by EdNutting** [comment]
Thank you for the suggestion, we will add this to our "definitely todo" list!

**Comment by rossng** [comment]
The chat sidebar is now collapsible. And we have duplicate issue for tracking a feature to make the chat bar fully resizeable - #161. Closing this issue in favour of that one.
