### ISSUE TITLE
Chat: Re-implement backend to meet real-time requirements

### ISSUE THREAD

**Issue by EdNutting** [clowdr-app/clowdr#26]
Chat is currently built upon Hasura Subscriptions, which although they run over a websocket, Hasura is ultimately just polling the Postgres db at a defined rate (1s -- though for much of POPL we had to throttle this to 1.5s). This isn't real time and murders our Postgres load.

We should re-implement chat on a socket.io / Redis layer on top of Heroku with a write-back buffer that batches writes into Postgres.

We should aim initially to:

* support chats with ~2,000 members, with 10% sending a message every 10s to be received by all others. This will be a sufficient target for our upcoming conferences. 
* have happens-before consistency, though eventual-consistency may be sufficient
* have the ability to scale the backend servers horizontally using Heroku's automated scaling

**Comment by mgree** [comment]
+1

From a UX perspective, EC seems important: making it seem as though your message has sent is psychologically important! If typical delays are <500ms with a long tail of 1s, happens-before is overkill.

**Comment by rossng** [comment]
I'll leave this issue in place to track the re-engineering of chat. But @EdNutting you may want to rewrite the description to reflect our current plans.

**Comment by EdNutting** [comment]
As of 09bf7eb, the new chat system is deployed based on RabbitMQ, Redis and socket.io. We are continuing our load testing but results have been sufficiently promising to justify releasing it to production.

Remaining items:

* Extended production-based load testing
* Implementation of unread counts
