### ISSUE TITLE
Chat unread counts and notifications when sidebar is closed

### ISSUE THREAD

**Issue by EdNutting** [clowdr-app/clowdr#269]
**Describe the bug**

The unread count that is supposed to show next to the My Chats text of the chats tab switcher sometimes does not appear.

The chats button does not indicate unread messages when the sidebar is closed.

Notifications do not show when the chat sidebar is closed but a particular chat has been selected.

**Additional context**

https://twitter.com/jbarroscandido/status/1394593139214651396?s=19

**Comment by jeandersonbc** [comment]
Thanks for opening an issue on it :)

Something that might also be considered would be showing the notification only for direct messages.
I think that, as a user, I wouldn't want to get "noise" from general announcements (Announcements, Help Desk, etc...)

**Comment by EdNutting** [comment]
* A fix for the missing unread count next to the My Chats title is now being deployed.
* The other items are less easy and will tackle in future.

**Comment by EdNutting** [comment]
I believe these issues have now been fixed. 

Note: Notifications can be turned off per-chat by using the bell icon. By default they appear only for DMs and Announcements. Announcements is mandatorily-subscribed at most conferences so that organisers can have a guaranteed way to contact all attendees in real time. This is a conference organiser choice as to whether to configure the Announcements chat like this or not)
