### ISSUE TITLE
When live stream is in "Picture in Picture" mode with screenshare/presenter, and screen share ends, go back to "auto layout" by default

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr#273]
When giving a live presentation, it's somewhat intuitive as a presenter that clicking "stop screenshare" will go back to the normal/auto layout - instead, it remains in PiP but with no video source going to where the screenshare had been.

**Comment by EdNutting** [comment]
This has become obsolete as part of the numerous layout control improvements over the last few months.
