### ISSUE TITLE
When the previously selected camera is not available, do not show generic "Please grant permission to view camera" screen

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr#276]
It looks like when we try to acquire media permissions, if the selected camera is not available, we show the "Please grant permissions to use the camera" box (even if it's already granted). This error gets triggered if, for instance, you are on Clowdr on a laptop and use your built-in webcam, then close the screen and plug in to a wired camera (or the other way around). I have seen a few other users get confused by this too.

**Comment by EdNutting** [comment]
Ah! Now this finally put me on the right track for what has been causing the "perpetually stuck with permissions denied" and needing to use "Choose cam/mic" to get out of it. We have been caching the chosen mic/cam but with no automatic "forget the chosen mic/cam" if someone just clicks "start cam/mic" (as opposed to going through the chooser modal). 

Temporary permissions vs "always" permissions can still get the browser into knots when combined with sudden removal of a device, but with the incoming fix refreshing the page will at least solve the issue. Whereas previously, refreshing would still leave you stuck in the "start -> perms denied" loop.
