### ISSUE TITLE
Toggle dark mode icon looks like a "settings" icon (minor) 

### ISSUE THREAD

**Issue by charguer** [clowdr-app/clowdr#3]
Another icon might be more appropriate.
Eventually, it would probably makes sense to have an actual "settings" button, opening up a list of possible settings, including toggle dark mode.

**Comment by EdNutting** [comment]
Thank you for raising this. We'll try to find a better icon.

**Comment by EdNutting** [comment]
This icon has been changed to a moon (filled/unfilled according to the current mode) and an explanatory tooltip has also been added.
