### ISSUE TITLE
Add mechanism to request user to refresh page

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr#31]
For various reasons, we might need to get a user to click “refresh” in clowdr. We need a system to 1: set these bits for each session of each user, and 2: cease all requests from that session until the page is refreshed.

Ed wrote in Slack:
> We probably just need a backend var that has a timestamp for 'last required refresh time' and a frontend timestamp in local storage that stores the last time we asked the user to refresh. And the rest is obvious.

I would suggest alternatively using semantic versioning for frontend deployments. Minor deployments do not require a refresh (but suggest to the user that they might want to click refresh to get the latest and greatest, or cancel and keep doing what they were doing), major deployments put up a modal warning, requiring a refresh and also cut off all requests until refresh occurs. This provides an easy way to do hot-fixes during an event and get people to hit refresh overnight, and to distinguish between “if this user doesn’t refresh our system will suffer for it” and “we have a new version of the shuffle space interface and we think you’ll find it better, but it’s not obligatory that you refresh”.

**Comment by EdNutting** [comment]
We now have a way to force-refresh the end-user's browser by changing a per-conference configuration var in the DB. 

I chose to do it per-conference for three reasons:

* It will allow us to refresh conferences at different times. I think this is important both for ensuring we don't suddenly interrupt an ongoing event but also for staggering the refreshes.
* It was convenient (we already have a conference-configuration table)
* The non-conference part of the app has very little code and is primarily reached when a user logs in (i.e. reloads via login) or signs up (i.e. reloads by first arrival). So there's (currently) no need to force a refresh outside of the conference part of the site.

The way this works is the user's browser polls the config var every 5 mins to look for a new version. If the version number is different, it refreshes. Eventually we may want to turn this into a "request the user to refresh" but that's more UI work than necessary right now.
