### ISSUE TITLE
Organisers should automatically have permissions on all elements

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#310]
When creating a conference, it is not obvious right now that an element permission needs to be added for the organisers group before anything can be done. This confused me because the 'add element' button wasn't doing anything at all! 

We should do this automatically since we already add the creator to the 'organisers' group automatically. 

Users who want a more advanced setup can go and modify the element permissions later.

**Comment by EdNutting** [comment]
Obsolete since the elimination of per-element security model.
