### ISSUE TITLE
[Profile] Users should be able to pick their website URL HTTP prefix

### ISSUE THREAD

**Issue by EdNutting** [clowdr-app/clowdr#312]
Report from Twitter: https://twitter.com/andrejbauer/status/1415679731345756166

* Users should be able to choose HTTP or HTTPS. 
* If someone pastes a full URL, we should detect whether they have included HTTP or HTTPS and set accordingly.

We force the HTTP(S) prefix for a good reason: it ensures users are putting in complete URLs and not potential traps like "mailto:" or simply urls lacking the prefix (which can cause links to go internally within Clowdr when they should direct users externally).

**Comment by nishit-prasad** [comment]
Hello! I am new and would like to work on this. Can I take this up?

Will be reviewing the docs to get me started.

**Comment by rossng** [comment]
Yes, that'd be great 🙂

The READMEs should get you through most of the setup process but there are some spots where you might need to ask us for help. If you like, I'm happy to invite you to our Slack instance where you can ask questions.

**Comment by nishit-prasad** [comment]
Awesome. Thank you so much. Please assign it to me and also share me the slack instance link.
Also if you don't mind, please do let me know the right channel inside Slack where I can ask questions.

Again, appreciate it!

**Comment by rossng** [comment]
Sent it to the email address attached to your Git commits.

The Slack's a bit disorganised right now - we'll get round to cleaning things up eventually. #onboarding is a good place to put questions.

**Comment by nishit-prasad** [comment]
Thank you! Appreciate it.
