### ISSUE TITLE
Mobile layout <-> desktop layout switch causes Vonage room disconnect

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#318]

**Comment by EdNutting** [comment]
This is likely caused by the entire app switching from the V2 implementation to the V1 implementation of AppPage (or vice versa).

The proper solution is probably to make the new UI mobile friendly and finally free ourselves of the old one. And thus avoid the switching scenario entirely.

**Comment by EdNutting** [comment]
This issue was caused by what I described and fixed as part of our implementation/deployment in January.
