### ISSUE TITLE
Include documentation for creating a conference code

### ISSUE THREAD

**Issue by shawnsp** [clowdr-app/clowdr#331]
**Is your feature request related to a problem? Please describe.**
Add an instruction on how to create a conference code (demo code)

**Describe the solution you'd like**
Add the instruction after the Local Development section in the main README.md

**Comment by rossng** [comment]
Yes, a very good point! We've been missing this the whole time.

Long term, we would like to add a super admin UI and onboarding flow, but I think adding a paragraph to the docs would be very useful for now.

If there were any other things that would have made your setup experience easier, please feel free to submit issues for those too 🙂

**Comment by rossng** [comment]
Closed by Shawn's PR: #333
