### ISSUE TITLE
Users report that no chat notification is issued for the first message

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#355]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EdNutting** [comment]
Can't reproduce the issue as described but I think this is a slightly misleading report. I have reproduced an issue that meant initial messages would not show an unread count. I can see how someone would use the language of the title of the issue to describe this.
