### ISSUE TITLE
Way to see talk when chairing Q&A

### ISSUE THREAD

**Issue by mgree** [clowdr-app/clowdr#39]
Small, mutable video on the side would be nice. Tough to be a session chair when you haven't seen the talk!

**Comment by rossng** [comment]
This is somewhat related to #56, at least in terms of the concerns that it raises:

* Having a live stream on the page in the speakers'/backstage area consume bandwidth, which lowers the quality of the video chat going into the livestream.
* Many presenters do not wear headphones, and having a (non-muted) stream preview causes a feedback loop

I do see the utility in being able to watch the talk that you are about to chair the Q&A for. Perhaps there is a solution I haven't thought of that sits somewhere between 'display the livestream while the user is backstage' and 'the user should just open the livestream in a new tab'.

**Comment by mgree** [comment]
I'm embarrassed to admit it didn't even occur to me open the same talk in another window. Perhaps including an explicit link and suggesting as much to session chairs would be good.

Muting the livestream by default would be good; I can also imagine having it auto-turn off 15-30s before the handover (or buffer in advance to play those parts without needing them streamed).

**Comment by EdNutting** [comment]
Closing in favour of #340
