### ISSUE TITLE
Room garbage collection

### ISSUE THREAD

**Issue by mgree** [clowdr-app/clowdr#41]
Lots of rooms hang around after their events. Make a flag? Have a GC button that lets admins destroy rooms that (a) have no future events scheduled, (b) aren't DMs or whatever, and (c) haven't been used in X minutes.

**Comment by EdNutting** [comment]
Between our recent changes to clean up rooms (a LOT), the rework of the auto-generated "speaker's rooms" (previously Q&A rooms), the additional cleanup of chats vs rooms, and the separate issuing that is tracking the need for us to re-add Ephemeral rooms, I think this issue can be closed now.
