### ISSUE TITLE
Subtitles are generated twice, overwriting the ones edited by the user.

### ISSUE THREAD

**Issue by FlyingPumba** [clowdr-app/clowdr#412]
**Describe the bug**
Subtitles generated twice, overwriting the ones I had reviewed and edited.

**To Reproduce**
I'm not sure what are the steps to reproduce this.

**Expected behavior**
Subtitles should only be generated once.
An extra check should be made to **not** overwrite subtitles if they were edited by the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/1159078/167295877-4fe377f3-c1a4-4b93-9a11-f078dc172dc9.png)

**Additional context**
The submission is for AST 22, if it helps.

**Comment by EdNutting** [comment]
Thank you for reporting this. This was not a bug but the result of a data migration for ICSE 2022 for underlying performance reasons. 

Kind regards,
Ed

**Comment by FlyingPumba** [comment]
For the future, maybe include the edited subtitles in the data migration.
I spent some time editing them online (which worked great, btw), and it didn't occur to me to download them afterwards since they were "saved" successfully. Now I have to work on them again from scratch.
