### ISSUE TITLE
Miscellaneous small improvements to shuffle spaces 

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#44]
- [x] When you get moved from the waiting queue into the Join Room page, you should get an audible signal (in case you have switched to looking at email while waiting).
- [x]  Instead of "Rooms limited to..." it should say "Rooms will reshuffle after X minutes"
- [x]  When it goes into "Sorry, it may not be possible to match you with anyone at the moment" mode, it should either tell me that it is still trying to match me or else give me a button to leave.
- [x]  "Please wait" should be renamed to "Waiting for more people to join"

**Comment by rossng** [comment]
Split tasks out to individual issues.
