### ISSUE TITLE
Limit access to speakers' area to authorised attendees

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr#52]
This was quite unsettling for the UCI event: many participants ended up in the video rooms, and we had no way of kicking them out. Luckily they didn't turn on their cameras, but they could have _easily_ disrupted the whole thing!
There are permissions; we need to make them work, at least for livestream video rooms.

**Comment by EdNutting** [comment]
The controls for who can enter video rooms got switched off for POPL because the UX was too confusing. We will add them back in as-and-when we have the time to go over the Room Page UX.

**Comment by bcpierce00** [comment]
Not sure whether this belongs in Sprint 0 or Sprint 1 (= Milestone 2.0.0).  Leaving in 0 for now.

**Comment by rossng** [comment]
Access controls are re-enabled now, at least in the UI. Need to check whether it is enforced in the backend.
