### ISSUE TITLE
Chat layout doesn't work well on small screens

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr#53]
This is what a video room looks like in a small laptop:
![image](https://user-images.githubusercontent.com/109621/107154019-7b3c5980-6968-11eb-8d71-d8de352e8f93.png)

The chat window becomes inaccessible. One needs to scroll down to see it, but this makes the video area also scroll:
![image](https://user-images.githubusercontent.com/109621/107154189-7e841500-6969-11eb-8ea9-d27349b5b537.png)

For reference, here is what Twitch does on the same laptop:
![image](https://user-images.githubusercontent.com/109621/107154199-8e9bf480-6969-11eb-80e9-fbc69c284707.png)

**Comment by EdNutting** [comment]
Is this fixed now?
