### ISSUE TITLE
Improve speaker backstage pre-join experience

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#55]
One unanticipated issue with five-minute talks is that five minutes is a
     very short amount of time for authors to find their way backstage and have
     a conversation with the session chair about sound, Q&A protocol, etc.

Ed: Yes. Originally the UI Ross built allowed you to join any distance in advance of the Q&A. BUT: The list of talks became horrifically confusing so I told him to cut it down to just the current and next talk. We need to revisit the system for how people find rooms.

**Comment by rossng** [comment]
We've made the pre-join time a bit longer, but it still needs significant refactoring.
