### ISSUE TITLE
Show some form stream preview to people in the speakers' area

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#56]
We really need to solve the problem of "Person who is speaking has the     livestream tab open so the audio loops" -- not just by giving clear     instructions, but by making it impossible.

People were consistently confused by the distinction between the     livestream broadcast and what they could see happening the Q&A room     (i.e., the source of the livestream).  IMO we should explicitly show     them a muted thumbnail of the livestream in the Q&A room, with a note     right next to it saying that there is a delay.  This is the best way to     make clear that there are two separate things and how they relate. (You can get to it in another tab, and     clearly speakers have been, but obviously we don't want them to do     that because it creates an audio loop!)

Ed:
 * Yes. Originally the UI Ross built allowed you to join any distance in advance of the Q&A. BUT: The list of talks became horrifically confusing so I told him to cut it down to just the current and next talk. We need to revisit the system for how people find rooms.
* We already log server side when someone is participating in a room. We need to pull this into the UI and prevent (i.e. make completely impossible) the stream playing audio (with a suitable warning message) when the user is connected to the same room that the stream is playing back. 
* Yes we need a "sanctioned" way for users to see what they're streaming.

**Comment by EdNutting** [comment]
@rossng Given the Vonage stream layout is controlled by CSS, can we reasonably replicate that client side (using the elements in the Vonage room) to replicate the view of the stream (but in real-time) in the backstage room? And simply have "extra available video streams" in a scroller or grid shown below the "stream preview"?

**Comment by rossng** [comment]
Yes, that's what I'm thinking too. I don't want to pull in the actual HLS stream because a) it's delayed and that will confuse people and b) the extra bandwidth usage will probably cause issues in the video call.

**Comment by EdNutting** [comment]
Closing in favour of #340
