### ISSUE TITLE
[Feature] Pin specific Rooms

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr#6]
Possibly useful feature during coffee breaks

**Comment by EdNutting** [comment]
Pinning the room's chat will effectively pin the room. What we need to do is clean up this aspect of the sidebar and room layout so it's more obvious what is available.

**Comment by rossng** [comment]
We now have quite good UI around pinned chats in the right sidebar, and priority can be used to 'pin' social rooms in the the left sidebar.

One remaining issue is that the room data in the sidebar doesn't update with occasional background polling, so you have to refresh to see changes. I've split this out to its own issue, #203
