### ISSUE TITLE
Text chat improvements

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#60]
- [x] The distinction between "Room chats" and "Item chats" does not make much sense for workshops where all content is live.  I strongly suggest that we change the platform to support "Room chat only" rooms.
- [x] Similarly, we may need to re-reconsider how the chats are displayed.  Showing just the room chat is (much!) easier for people to understand, but then people can't look back for questions from the paper chat from before the talk started.
- [x] When chat messages are read, the sidebar unread count should be cleared (locally) immediately.  Otherwise it takes too long to get updated and looks buggy.
- [x] Similarly, chat messages should be displayed locally immediately.
- [x] Forcing a question to end with a question mark seems gratuitously constraining.
- [x] The term "reflection" persistently confuses me.  How about "Linking chats" and "unlinking chats".  (Also, the change-over in the chat uses a huge amount of vertical space.  Could we have just one brown line and put the three buttons above / below
- [x] I don't like having an "answer mode" in chats -- it's confusing.  There should just be a button (like now) on the question, and a similar "Answer again" button on each answer.
- [x] When the Q&A room switches to spinoff mode, it should show the paper chat, not the room chat (maybe fixed already?)
- [ ] The chat system is too complicated overall.

Ed:
* We need to discuss whether Item chats make sense at all or not.
* Unread counts as per previous points - avoiding db load was the reason for this, nothing else.
* Displaying messages "immediately" -- again, we need to rebuild chat to be properly real-time. See slack conversations and existing Github issue(s). This includes inserting messages client side into the list and removing them again if they fail to send.
* We can adjust the types of message however we feel like
* I think we should consider ditching the linking of chats in favour of something smarter, cleaner and less baffling to users. I have an idea, will discuss Tuesday.

**Comment by EdNutting** [comment]
FPGA have pointed out that the reflection markers in the chat may just be unnecessary. If we just didn't include them, but continued doing the reflection "silently", from an attendee's point of view everything (might) "just work" and wouldn't need any explanation.

**Comment by bcpierce00** [comment]
That seems very worth thinking about!!!  The reflection stuff is very
confusing to users.

**Comment by EdNutting** [comment]
I have disabled the sending of the duplication marker messages for now.

**Comment by EdNutting** [comment]
I have disabled the check that forces users to use a question mark in their question.

**Comment by EdNutting** [comment]
I have hidden the button for selecting "answer mode" so now you just have to click "Answer this question" on the question chat message.

**Comment by rossng** [comment]
> The term "reflection" persistently confuses me. How about "Linking chats" and "unlinking chats". (Also, the change-over in the chat uses a huge amount of vertical space. Could we have just one brown line and put the three buttons above / below

This is now eliminated. We might re-introduce a viual indicator at some point, but we'll reconsider it as and when.

**Comment by rossng** [comment]
>  When the Q&A room switches to spinoff mode, it should show the paper chat, not the room chat (maybe fixed already?)

This is done as part of unifying spinoff rooms and item discussion rooms.

**Comment by rossng** [comment]
> The chat system is too complicated overall.

I suspect the changes to the sidebars have significantly improved the perception of chat complexity.

I imagine there might be some remaining complexities in the chat UI, so would be interested to hear what you think these are @bcpierce00. I'm going to close this issue but please open new issues for any specific improvements that could be made!
