### ISSUE TITLE
Better A/V presence indicators for breakout rooms

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#63]
- [x] It is hard (maybe not even possible) to see which people in a breakout room have their     audio off.  This would be useful information.
- [x] In large (>10) breakout rooms, it would be great to be able to distinguish     between people with video intentionally off and people whose video is     simply not being shown by Vonage

Ed:
* Would require us to build a suitable backend layer (i.e. not the DB) to store it in real-time. The backend aspect is the same issue as chat.
* Agreed - don't know how hard this would be. Ross could say.

**Comment by rossng** [comment]
We have now implemented the microphone on/off indicators for breakout rooms. I think this satisfies item 1.
