### ISSUE TITLE
Ui nits (high priority)

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#76]
- [x] One way to make sure people notice the hamburger icon (before we're ready to make the sidebar on-by-default) would be to turn it into a button with a text label (e.g., "More...").
- [x] Tweak the colors on the room / talk so that the chat area is visually distinct from the rest of the page.
- [x] Similarly, the background colors on the "Join room" page are too similar (the two blues are too close), and the area for composing messages is hard to find -- needs an outline or something to help people find it.
- [x] The Rooms overview is laid out very inefficiently -- way too much whitespace and too little information on the page without scrolling.
- [x] We need to better distinguish the "In chat area of room" (i.e., I'm on the "joining room" / video preview page, I can see and interact with the chat, but I can't see any video) and "Actually joined to the room" modes.  One problem is that the word "Room" has multiple senses.  We need to distinguish the Chat area from the Video area, both visually and terminologically.  One thing that would help a lot -- and make chat rooms more useful when just chatting -- and (I hope) be quite simple to implement -- is to automatically make the video area much smaller when it's in the "Preview your camera" mode.  (Ed: I agree on resizable chat as per previous points. I'm not sure I see what distinction you're making about being "in chat area" vs anything else. It feels like a non-existent distinction. BCP: The distinction is that one takes a single click to get to, while the other requires an additional click.)
- [x] Private and small-group rooms should be marked "private" in the rooms list so that people don't get the impression that their private rooms are being shown to other people.  (Ed: Technically they are, using the "lock" symbol, but I agree it's not obvious enough. They need to be in their own separate area.  And the rooms page needs re-working.)

**Comment by EdNutting** [comment]
- [ ] Should the sidebar be open by default? 
  * If so, instead of being an overlay, it should probably be an expander?

**Comment by bcpierce00** [comment]
Yes to both!!!

**Comment by bcpierce00** [comment]
It should definitely *not* be an overlay, no matter what.

**Comment by EdNutting** [comment]
We've made a lot of progress on these items this week. Could you outline which bits are left to work on? (Good to have an 'external' perspective!)

**Comment by bcpierce00** [comment]
* The background colors issues are much better.
* In general, I find many of our layouts wasteful of space -- I want almost everything a bit (or sometimes a lot, as in the rooms page) tighter.
* I'm still concerned about the "two clicks needed to join a room with video" issue -- it's clunky.  But it's not a showstopper for anyone the way it is.  For ordinary breakout rooms, this can be considered a low-priority conversation.  For presentation rooms I can't comment -- haven't played with the new flow enough.

**Comment by rossng** [comment]
All remaining tasks split to issues.
