### ISSUE TITLE
[UI] Scrolling down when there are too many participants in a room

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr#8]
Scrolling may get stuck, hiding the buttons to mute/unmute and activate/deactivate camera

**Comment by EdNutting** [comment]
Not sure if this remained an issue after we re-worked the video room layout since this was reported?

**Comment by EdNutting** [comment]
This has been resolved for certain in recent re-workings of the video rooms page. The layout is much cleaner and easier now.
