### ISSUE TITLE
Error page is shown when people aren't logged in

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr#81]
I have been invited for a conference, and I have signed up, and logged in. Due to inactivity, my computer logged off of Clowdr. When I restart it, I see this page:
![image](https://user-images.githubusercontent.com/109621/107805311-04adac00-6d1a-11eb-9890-c74d3e04dff4.png)

This should be replaced by another page that doesn't show an error, but simply: "please login"

**Comment by EdNutting** [comment]
I will fix this and at the same time review all our error pages as I think "page not found" has become over-used and there are lots of places where better errors could be displayed.

This is probably high priority. 

I think #20 is related.

**Comment by EdNutting** [comment]
Recent commits (which also incorporated feedback from CLSummit for linking to external registration sites) have resolved this issue I think?
