### ISSUE TITLE
Can't access conference despite invitation

### ISSUE THREAD

**Issue by goldfirere** [clowdr-app/clowdr#88]
I'm expecting to attend the wg2.8 conference next week, but I can't access the conference page.

* I received the emailed invitation.
* When I follow the link, I briefly see a page headed "Accepting Invitation..."
* Then, at URL https://app.clowdr.org/conference/wg2.8, I see "Sorry, we couldn't find that page." with "You may not have received or accepted your invitation to the conference you're trying to access. ...".
* There is a button "Go to home page". Clicking it does nothing; it seems to bring me to the same URL I am already at.
* Manually going to app.clowdr.org (by typing in the URL) gets me to a page with a WG2.8 button. (I see a button with tooltip "Log out" toward the top right, so I think I'm indeed logged in.) Clicking the WG2.8 button brings me back to "Sorry, we couldn't find that page." 
* Going back to app.clowdr.org, I can click on "Use invite code", so I do that.
* Copying and pasting the invite code from my invitation email just repeats the first process above, with a brief "Accepting invitation..." and then "Sorry, we couldn't find that page."

I'm now out of ideas. Help?

The invitation was sent to the email associated with this GitHub account, rae@richarde.dev, and I'm running Google Chrome (Version 88.0.4324.182 (Official Build) (x86_64)) on a Mac (MacOS 10.13.6 (17G14033)).

Thanks!

**Comment by bcpierce00** [comment]
Thanks for the bug report.  We'll get this sorted out tomorrow, Richard.

**Comment by bcpierce00** [comment]
BTW, I do see you listed as a registered attendee, so something worked!

    - B

**Comment by EdNutting** [comment]
The system did what it was supposed to - the OP hadn't been added to any Groups, so was added to the conference but not granted access to any of the conference pages.

Issue #20 is related to this.

**Comment by bcpierce00** [comment]
Richard, please let us know if you're still having any difficulties.

**Comment by goldfirere** [comment]
All set for me -- thanks. But it's not clear to me whether I should close the ticket. But I am now a satisfied customer.

**Comment by bcpierce00** [comment]
Thanks, Richard!
