### ISSUE TITLE
The Schedule page should be disabled if there is nothing on the schedule

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#90]
... because the current page is not useful, and looks ugly / wrong at first sight:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/7014411/108707248-bea4d500-74dd-11eb-8ab7-ba4533706032.png">

**Comment by rossng** [comment]
It will always be possible to access the page directly via the URL -  we can't prevent that unless we do GraphQL requests inside the page router (bad idea!).

Maybe we should just display 'no events in schedule' or some similar message. Hiding the button from the sidebar is easier but might also confuse organisers.

**Comment by bcpierce00** [comment]
Displaying “No scheduled events” if people reach the page by a sneaky path is fine. But I still really want to suppress the sidebar header if there is no schedule. This is consistent with all the other things we don’t display if they are not relevant

**Comment by EdNutting** [comment]
Given the schedule now says "no events" and the changes in the UI, this is essentially a non-issue now.

**Comment by bcpierce00** [comment]
I'm not sure what UI changes you mean, @EdNutting, but I'm not 100% convinced this is a non-issue.  Though perhaps it's just an instance of a more general conversation about "skinning" Clowdr for various specialized uses -- e.g., for meetings that have no schedule as such (e.g., meetings that are just a single event).
