### ISSUE TITLE
Top-right buttons should be rearranged

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#91]
The row of buttons on the top right are confusing for users (and potentially annoying) because they mix two groups of functionality: control over the UI (the dark-mode and open/close buttons) and controls for leaving the conference (log-out and my-conferences buttons).  

The my-profile button is a bit of a different thing, but I'm going to say that it belongs with the latter group because it takes you to a different page.

The potential for confusion comes from having buttons that do things to the current page (the rightmost two) together with buttons for taking you away from the current page or away from the whole conference.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/7014411/108707619-4e4a8380-74de-11eb-852f-bf644676a7cb.png">

Suggested fix: 
* Leave a little space (two button widths would be enough) between the first and second groups.
* Consider whether we really want to have a log-out button at all.  (Do we really expect people to use it?  When/why?  If log-out functionality is really needed, could it be provided just on the my-conferences page?)

**Comment by bcpierce00** [comment]
I like this.

**Comment by EdNutting** [comment]
This has been done.
